### ISSUE TITLE
Shell commands freeze on execution

### ISSUE THREAD

**Issue by X1nto** [topjohnwu/Magisk#3712]
after updating to v21.3 shell scripts just freeze on execution with no feedback given at all, v21.2 worked fine. We found out the issue appeared after `76061296` canary build. Logs also spam something about broken pipe.

Here are snippets that use LibSU in order to run shell commands:

https://github.com/YTVanced/VancedManager/blob/dev/app/src/main/java/com/vanced/manager/utils/Extensions.kt#L92-L97
https://github.com/YTVanced/VancedManager/blob/dev/app/src/main/java/com/vanced/manager/utils/PackageHelper.kt#L198-L221

Although it seems like not everything is broken:
https://github.com/YTVanced/VancedManager/blob/dev/app/src/main/java/com/vanced/manager/utils/PackageHelper.kt#L144-L150 

Logs:
[Magisk Log](https://drive.google.com/file/d/1lWwAXgFB3zCyjAjogpFpSMMXM0L_ga5n/view?usp=sharing)

**Comment by Haus3master** [comment]
Logs spamming something about broken pipe seems to be common, even I too have it (I'm on Magisk canary 2f5331ab (21301))

**Comment by topjohnwu** [comment]
It should be fixed in the latest canary, please check and verify

**Comment by X1nto** [comment]
Works on latest canary

**Comment by GerardEarley** [comment]
Ive installed the latest canary Magisk 79140c76 (21305) and Magisk Manager b5b2e03 (4831) (15)  on to my Oneplus 9.0.9 and I'm afriad the reported issue with installing the latest version of Vanced (15.42.32) via their Vanced Manager v2.2.2 is not resolved.

See attached logs
[magisk_log_2021-01-17T11_54_54Z.log](https://github.com/topjohnwu/Magisk/files/5826036/magisk_log_2021-01-17T11_54_54Z.log)
