### ISSUE TITLE
Phone crashes around 10sec after boot with Magisk installed

### ISSUE THREAD

**Issue by nanoSwiss** [topjohnwu/Magisk#7527]
Device: Motorola edge 20 Pro
Android version: Android 13 (LineageOS 20-20231113-NIGHTLY-pstar)
Magisk version name: Magisk 26.4 debug
Magisk version code: 26401

Setup/Fluff:
So originally i ran LineageOS 19 with Magisk v24.something on my phone previously. after it got water damaged it was stuck crashing after 10sec in to the OS. I replaced the mainboard and Battery and installed LineageOS 20 on it. **after which it ran fine**. _(I have no idea how, why or if there is any correlation with the water damage but i thought id mention it since it seamed a weird coincidence.)_

Problem:
So next i installed Magisk 26.4 stable via the LineageOS recovery like i always did with my phones. after which it crashed around 10sec in to the OS after booting. (i can log in fine, Magsik reports everything is ok, apps work fine and then it crashes and reboots) so i wiped it, and reinstalled it using the patched boot.img, (attached below) same problem, then i tried Magisk debug, as mentioned in #7491, same problem, then i tried Magisk 24.3 with i knew should work with my phone as it previously did same issue.

[magisk_log_2023-11-16T13.51.02.log](https://github.com/topjohnwu/Magisk/files/13378196/magisk_log_2023-11-16T13.51.02.log)
[cat prog_mounts.txt](https://github.com/topjohnwu/Magisk/files/13378197/cat.prog_mounts.txt)
[bugreport-pstar_retail-TQ3A.230901.001-2023-11-16-13-02-46.zip](https://github.com/topjohnwu/Magisk/files/13378198/bugreport-pstar_retail-TQ3A.230901.001-2023-11-16-13-02-46.zip)
[bugreport-pstar_retail-TQ3A.230901.001-2023-11-16-13-02-46-dumpstate_log-7464.txt](https://github.com/topjohnwu/Magisk/files/13378199/bugreport-pstar_retail-TQ3A.230901.001-2023-11-16-13-02-46-dumpstate_log-7464.txt)
[dumpstate-stats.txt](https://github.com/topjohnwu/Magisk/files/13378200/dumpstate-stats.txt)

I somehow cant upload the boot.img because they are too big (.zip = 31mb / .img = 98mb each) Here is the Google drive link: https://drive.google.com/drive/folders/1Rd-7vsM_8jCbF7Qm85nHSbDx7Znn9-Ta?usp=sharing
If there is anything important missing let me know.

At this point i am dumbfounded at what the problem is, or why the problem is occurring, thanks in advance for any help.

**Comment by HarshadDhokale** [comment]
The issue is with the latest stable magisk 26.4 manager apk. Package installer installs magisk manager with some issues. 
These steps worked for me, maybe it will work for you too.
(https://raw.githubusercontent.com/topjohnwu/magisk-files/canary/app-debug.apk)
1. Rename debug apk to zip and flash it through recovery. Install debug apk in os via package installer.
2. Change the update channel to stable.
3. Install the latest manager ![Screenshot_20231116-064216_Magisk Root~3.png](https://github.com/topjohnwu/Magisk/assets/105629462/0e927e47-a5f6-4968-a57c-6629a4032e5b)
4. Direct install magisk from manager.

**Comment by canyie** [comment]
The only one crash I found in your log:
```
11-16 12:58:08.162  1000  1273  1273 F libc    : Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 1273 (vendor.lineage.), pid 1273 (vendor.lineage.)
11-16 12:58:08.233  1000  1413  1413 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
11-16 12:58:08.235  1000  1413  1413 F DEBUG   : LineageOS Version: '20.0-20231113-NIGHTLY-pstar'
11-16 12:58:08.235  1000  1413  1413 F DEBUG   : Build fingerprint: 'motorola/pstar_retail/pstar:12/S1RAS32.41-20-16-11/2d77a8-3df6d:user/release-keys'
11-16 12:58:08.235  1000  1413  1413 F DEBUG   : Revision: 'pvt'
11-16 12:58:08.236  1000  1413  1413 F DEBUG   : ABI: 'arm64'
11-16 12:58:08.236  1000  1413  1413 F DEBUG   : Timestamp: 2023-11-16 12:58:08.202806169+0100
11-16 12:58:08.236  1000  1413  1413 F DEBUG   : Process uptime: 1s
11-16 12:58:08.236  1000  1413  1413 F DEBUG   : Cmdline: /vendor/bin/hw/vendor.lineage.livedisplay@2.1-service.moto_kona
11-16 12:58:08.236  1000  1413  1413 F DEBUG   : pid: 1273, tid: 1273, name: vendor.lineage.  >>> /vendor/bin/hw/vendor.lineage.livedisplay@2.1-service.moto_kona <<<
11-16 12:58:08.236  1000  1413  1413 F DEBUG   : uid: 1000
11-16 12:58:08.236  1000  1413  1413 F DEBUG   : signal 6 (SIGABRT), code -1 (SI_QUEUE), fault addr --------
11-16 12:58:08.236  1000  1413  1413 F DEBUG   : Abort message: 'PictureAdjustment backend not ready, exiting.'
11-16 12:58:08.236  1000  1413  1413 F DEBUG   :     x0  0000000000000000  x1  00000000000004f9  x2  0000000000000006  x3  0000007fffe693e0
11-16 12:58:08.236  1000  1413  1413 F DEBUG   :     x4  64711f736e6d1f63  x5  64711f736e6d1f63  x6  64711f736e6d1f63  x7  7f7f7f7f7f7f7f7f
11-16 12:58:08.236  1000  1413  1413 F DEBUG   :     x8  00000000000000f0  x9  00000079a178da90  x10 0000000000000001  x11 00000079a17cd4ac
11-16 12:58:08.236  1000  1413  1413 F DEBUG   :     x12 0000007fffe69360  x13 000000000000002e  x14 b4000077c1596210  x15 00000000341555ac
11-16 12:58:08.236  1000  1413  1413 F DEBUG   :     x16 00000079a1835d68  x17 00000079a1811120  x18 00000079a6e9e000  x19 00000000000004f9
11-16 12:58:08.236  1000  1413  1413 F DEBUG   :     x20 00000000000004f9  x21 00000000ffffffff  x22 00000079a6203000  x23 00000079a6203000
11-16 12:58:08.236  1000  1413  1413 F DEBUG   :     x24 0000000000000000  x25 0000000000000000  x26 0000000000000000  x27 0000000000000000
11-16 12:58:08.236  1000  1413  1413 F DEBUG   :     x28 0000000000000000  x29 0000007fffe69460
11-16 12:58:08.236  1000  1413  1413 F DEBUG   :     lr  00000079a17be3e8  sp  0000007fffe693c0  pc  00000079a17be414  pst 0000000000001000
11-16 12:58:08.236  1000  1413  1413 F DEBUG   : backtrace:
11-16 12:58:08.236  1000  1413  1413 F DEBUG   :       #00 pc 0000000000052414  /apex/com.android.runtime/lib64/bionic/libc.so (abort+168) (BuildId: d0ebc428e0c038de101c2826d3b71953)
11-16 12:58:08.236  1000  1413  1413 F DEBUG   :       #01 pc 000000000000642c  /system/lib64/liblog.so (__android_log_default_aborter+16) (BuildId: 7dea2c4ace3a6b425668afcadb2a832e)
11-16 12:58:08.236  1000  1413  1413 F DEBUG   :       #02 pc 0000000000016648  /apex/com.android.vndk.v33/lib64/libbase.so (android::base::LogMessage::~LogMessage()+356) (BuildId: 7624afd5fb57bba16a373dd2b69838dc)
11-16 12:58:08.236  1000  1413  1413 F DEBUG   :       #03 pc 0000000000004258  /vendor/bin/hw/vendor.lineage.livedisplay@2.1-service.moto_kona (vendor::lineage::livedisplay::V2_0::sdm::PictureAdjustment::PictureAdjustment(std::__1::shared_ptr<vendor::lineage::livedisplay::V2_0::sdm::SDMController>)+248) (BuildId: 6c8a36a2debdc5364323cc99b69cce3e)
11-16 12:58:08.236  1000  1413  1413 F DEBUG   :       #04 pc 0000000000005af0  /vendor/bin/hw/vendor.lineage.livedisplay@2.1-service.moto_kona (RegisterAsServices()+124) (BuildId: 6c8a36a2debdc5364323cc99b69cce3e)
11-16 12:58:08.236  1000  1413  1413 F DEBUG   :       #05 pc 0000000000006188  /vendor/bin/hw/vendor.lineage.livedisplay@2.1-service.moto_kona (main+112) (BuildId: 6c8a36a2debdc5364323cc99b69cce3e)
11-16 12:58:08.236  1000  1413  1413 F DEBUG   :       #06 pc 000000000004a878  /apex/com.android.runtime/lib64/bionic/libc.so (__libc_init+100) (BuildId: d0ebc428e0c038de101c2826d3b71953)
```

But I don't think this one was caused by Magisk or either causes the phone to reboot. 
Currently Both the latest stable build (v26.4) and the latest canary/debug build are known to have some bugs that have been fixed on master, maybe it is the reason. I suggest you try the [latest CI build](https://github.com/topjohnwu/Magisk/actions/runs/6820908782).

**Comment by nanoSwiss** [comment]
@HarshadDhokale, Thank you for your suggestion, today i tried this out like you described but i still get the same issue, @canyie i tried the app-release.apk and app-debug.apk from the page you linked, but it made no difference. Here are some more logs i made with the debug.apk flashed thru lineage recovery, i could not finish the installation with the manager app, because the phone doesn't stay on long enough.  [bugreport.zip](https://github.com/topjohnwu/Magisk/files/13391861/bugreport.zip)

i also made a ¨shortish¨ video showcasing the crashes and the rebooting loop. I made the video while using the app-debug.apk @HarshadDhokale  provided. in the video i also showcase the phone staying on as soon as i remove magisk thru the manager app. I again uploaded everything on the Google Drive folder.
https://drive.google.com/drive/folders/1Rd-7vsM_8jCbF7Qm85nHSbDx7Znn9-Ta?usp=sharing

i also just noticed (at least with the magisk-debug.apk from the latest ci build) that i now cant shut the phone down normally as it just reboots again.

**Comment by canyie** [comment]
Files seems to be corrupted. `bugreport-pstar_retail-TQ3A.230901.001-2023-11-17-13-34-17.zip` is 0KB and cannot be decompressed.
